{hand: "Royal Flush" , rank:1},
{hand: "Straight Flush King High", rank:  2};
{hand: "Straight Flush Queen High", rank: 3 };
{hand: "Straight Flush Jack High", rank:  4};
{hand: "Straight Flush Ten High", rank:  5};
{hand: "Straight Flush Nine High", rank: 6 };
{hand: "Straight Flush Eight High", rank: 7 };
{hand: "Straight Flush Seven High", rank: 8 };
{hand: "Straight Flush Six High", rank: 9 };
{hand: "Straight Flush Five High", rank: 10 };
{hand: "Four Aces", rank: 11 };
{hand: "Four Kings", rank: 12 };
{hand: "Four Queens", rank: 13 };
{hand: "Four Jacks", rank:  14};
{hand: "Four 10's", rank:  15};
{hand: "Four 9's", rank:  16};
{hand: "Four 8's", rank:  17};
{hand: "Four 7's", rank:  18};
{hand: "Four 6's", rank:  19};
{hand: "Four 5's", rank:  20};
{hand: "Four 4's", rank:  21};
{hand: "Four 3's", rank:  22};
{hand: "Four 2's", rank:  23};
{hand: "Full House Aces over Kings", rank:  24};
{hand: "Full House Aces over Queens", rank:  25};
{hand: "Full House Aces over Jacks", rank:  26};
{hand: "Full House Aces over 10's", rank: 27 };
{hand: "Full House Aces over 9's", rank:  28};
{hand: "Full House Aces over 8's", rank:  29};
{hand: "Full House Aces over 7's", rank:  30};
{hand: "Full House Aces over 6's", rank:  31};
{hand: "Full House Aces over 5's", rank:  32};
{hand: "Full House Aces over 4's", rank:  33};
{hand: "Full House Aces over 3's", rank:  34};
{hand: "Full House Aces over 2's", rank:  35};
{hand: "Full House Kings over Queens", rank:36  };
{hand: "Full House Kings over Jacks", rank:  37};
{hand: "Full House Kings over 10's", rank: 38 };
{hand: "Full House Kings over 9's", rank:  39};
{hand: "Full House Kings over 8's", rank:  40};
{hand: "Full House Kings over 7's", rank:  41};
{hand: "Kings over 6's", rank:  42};
{hand: "Full House Kings over 5's", rank:  43};
{hand: "Full House Kings over 4's", rank:  44};
{hand: "Full House Kings over 3's", rank: 45 };
{hand: "Kings over 2's", rank:  46};
{hand: "Full House Queens over Jacks", rank:  47};
{hand: "Full House Queens over 10's", rank:  48};
{hand: "Full House Queens over 9's", rank:  49};
{hand: "Full House Queens over 8's", rank:  50};
{hand: "Full House Queens over 7's", rank:  51};
{hand: "Full House Queens over 6's", rank:  52};
{hand: "Full House Queens over 5's", rank:  53};
{hand: "Full House Queens over 4's", rank:  53};
{hand: "Full House Queens over 3's", rank:  54};
{hand: "Full House Queens over 2's", rank:  55};
{hand: "Full House Jacks over 10's", rank:  56};
{hand: "Full House Jacks over 9's", rank:  57};
{hand: "Full House Jacks over 8's", rank:  58};
{hand: "Full House Jacks over 7's", rank:  59};
{hand: "Full House Jacks over 6's", rank:  60};
{hand: "Full House Jacks over 5's", rank: 61 };
{hand: "Full House Jacks over 4's", rank:  62};
{hand: "Full House Jacks over 3's", rank:  63};
{hand: "Full House Jacks over 2's", rank: 64 };
{hand: "Full House 10's over 9's", rank:  65};
{hand: "Full House 10's over 8's", rank:  66};
{hand: "Full House 10's over 7's", rank:  67};
{hand: "Full House 10's over 6's", rank: 68 };
{hand: "Full House 10's over 5's", rank:  69};
{hand: "Full House 10's over 4's", rank:  70};
{hand: "Full House 10's over 3's", rank:  71};
{hand: "Full House 10's over 2's", rank:  72};
{hand: "Full House 9's over 8's", rank:  73};
{hand: "Full House 9's over 7's", rank: 74 };
{hand: "Full House 9's over 6's", rank:  75};
{hand: "Full House 9's over 5's", rank:  76};
{hand: "Full House 9's over 4's", rank:  77};
{hand: "Full House 9's over 3's", rank:  78};
{hand: "Full House 9's over 2's", rank:  79};
{hand: "Full House 8's over 7's", rank: 80 };
{hand: "Full House 8's over 6's", rank: 81 };
{hand: "Full House 8's over 5's", rank:  82};
{hand: "Full House 8's over 4's", rank:  83};
{hand: "Full House 8's over 3's", rank:  84};
{hand: "Full House 8's over 2's", rank:  85};
{hand: "Full House 7's over 6's", rank:  86};
{hand: "Full House 7's over 5's", rank:  87};
{hand: "Full House 7's over 4's", rank:  88};
{hand: "Full House 7's over 3's", rank: 89 };
{hand: "Full House 7's over 2's", rank: 90 };
{hand: "Full House 6's over 5's", rank:  91};
{hand: "Full House 6's over 4's", rank: 92 };
{hand: "Full House 6's over 3's", rank:  93};
{hand: "Full House 6's over 2's", rank:  94};
{hand: "Full House 5's over 4's", rank:  95};
{hand: "Full House 5's over 3's", rank:  96};
{hand: "Full House 5's over 2's", rank:  97};
{hand: "Full House 4's over 3's", rank:  98};
{hand: "Full House 4's over 2's", rank:  99};
{hand: "Full House 3's over 2's", rank:  100};
{hand: "Flush Ace High", rank:  101};
{hand: "Flush King High", rank:  102};
{hand: "Flush Queen High", rank:  103};
{hand: "Flush Jack High", rank:  104};
{hand: "Flush 10 High", rank:  105};
{hand: "Flush 9 High", rank: 106 };
{hand: "Flush 8 High", rank:  107};
{hand: "Flush 7 High", rank:  108};
{hand: "Flush 6 High", rank:  109};
{hand: "Flush 5 High", rank:  110};
{hand: "Straight Ace High", rank: 111  };
{hand: "Straight King High", rank: 112 };
{hand: "Straight Queen High", rank:  113};
{hand: "Straight Jack High", rank:  114};
{hand: "Straight 10 High", rank:  115};
{hand: "Straight 9 High", rank:  116};
{hand: "Straight 8 High", rank:  117};  
{hand: "Straight 7 High", rank:  118};
{hand: "Straight 6 High", rank:  119};  
{hand: "Straight 5 High", rank: 120 };
{hand: "Three Aces", rank: 121 };
{hand: "Three Kings", rank:  122};
{hand: "Three Queens", rank:  123};
{hand: "Three Jacks", rank:  124};
{hand: "Three 10's", rank:  125};
{hand: "Three 9's", rank:  126};
{hand: "Three 8's", rank:  127};
{hand: "Three 7's", rank:  128};
{hand: "Three 6's", rank:  129};
{hand: "Three 5's", rank:  130};
{hand: "Three 4's", rank:  1311};
{hand: "Three 3's", rank:  132};
{hand: "Three 2's", rank:  133};
{hand: "Two Pair Aces over Kings", rank:  134};
{hand: "Two Pair Aces over Queens", rank:  135};
{hand: "Two Pair Aces over Jacks", rank:  136};
{hand: "Two Pair Aces over 10's", rank:  137};
{hand: "Two Pair Aces over 9's", rank:  138};
{hand: "Two Pair Aces over 8's", rank:  139};
{hand: "Two Pair Aces over 7's", rank:  140};
{hand: "Two Pair Aces over 6's", rank:  141};
{hand: "Two Pair Aces over 5's", rank:  142};
{hand: "Two Pair Aces over 4's", rank:  143};
{hand: "Two Pair Aces over 3's", rank:  144};
{hand: "Two Pair Aces over 2's", rank:  145};
{hand: "Two Pair Kings over Queens", rank: 146 };
{hand: "Two Pair Kings over Jacks", rank:  147};
{hand: "Two Pair Kings over 10's", rank:  148};
{hand: "Two Pair Kings over 9's", rank: 149 };
{hand: "Two Pair Kings over 8's", rank: 150 };
{hand: "Two Pair Kings over 7's", rank:  151};
{hand: "Two Pair Kings over 6's", rank:  152};
{hand: "Two Pair Kings over 5's", rank:  153};
{hand: "Two Pair Kings over 4's", rank:  154};
{hand: "Two Pair Kings over 3's", rank:  155};
{hand: "Two Pair Kings over 2's", rank:  156};
{hand: "Two Pair Queens over Jacks", rank: 157 };
{hand: "Two Pair Queens over 10's", rank:  158};
{hand: "Two Pair Queens over 9's", rank:  159};
{hand: "Two Pair Queens over 8's", rank:  160};
{hand: "Two Pair Queens over 7's", rank:  161};
{hand: "Two Pair Queens over 6's", rank:  162};
{hand: "Two Pair Queens over 5's", rank:  163};
{hand: "Two Pair Queens over 4's", rank:  164};
{hand: "Two Pair Queens over 3's", rank:  165};
{hand: "Two Pair Queens over 2's", rank: 166 };
{hand: "Two Pair Jacks over 10's", rank:  167};
{hand: "Two Pair Jacks over 9's", rank:  168};
{hand: "Two Pair Jacks over 8's", rank: 169 };
{hand: "Two Pair Jacks over 7's", rank:  170};
{hand: "Two Pair Jacks over 6's", rank: 171 };
{hand: "Two Pair Jacks over 5's", rank:  172};
{hand: "Two Pair Jacks over 4's", rank: 173 };
{hand: "Two Pair Jacks over 3's", rank:  174};
{hand: "Two Pair Jacks over 2's", rank:  175};
{hand: "Two Pair 10's over 9's", rank: 176 };
{hand: "Two Pair 10's over 8's", rank:  177};
{hand: "Two Pair 10's over 7's", rank:  178};
{hand: "Two Pair 10's over 6's", rank: 179 };
{hand: "Two Pair 10's over 5's", rank:  180};
{hand: "Two Pair 10's over 4's", rank:  181};
{hand: "Two Pair 10's over 3's", rank:  182};
{hand: "Two Pair 10's over 2's", rank: 183 };
{hand: "Two Pair 9's over 8's", rank: 184 };
{hand: "Two Pair 9's over 7's", rank:  185};
{hand: "Two Pair 9's over 6's", rank:  186};
{hand: "Two Pair 9's over 5's", rank: 187 };
{hand: "Two Pair 9's over 4's", rank:  188};
{hand: "Two Pair 9's over 3's", rank:  189};
{hand: "Two Pair 9's over 2's", rank: 190 };
{hand: "Two Pair 8's over 7's", rank:  191};
{hand: "Two Pair 8's over 6's", rank:  192};
{hand: "Two Pair 8's over 5's", rank:  193};
{hand: "Two Pair 8's over 4's", rank:  194};
{hand: "Two Pair 8's over 3's", rank:  195};
{hand: "Two Pair 8's over 2's", rank:  196};
{hand: "Two Pair 7's over 6's", rank:  197};
{hand: "Two Pair 7's over 5's", rank:  198};
{hand: "Two Pair 7's over 4's", rank:  199};
{hand: "Two Pair 7's over 3's", rank:  200};
{hand: "Two Pair 7's over 2's", rank:  201};
{hand: "Two Pair 6's over 5's", rank:  202};
{hand: "Two Pair 6's over 4's", rank: 203 };
{hand: "Two Pair 6's over 3's", rank:  204};
{hand: "Two Pair 6's over 2's", rank: 205 };
{hand: "Two Pair 5's over 4's", rank:  206};
{hand: "Two Pair 5's over 3's", rank:  207};
{hand: "Two Pair 5's over 2's", rank:  208};
{hand: "Two Pair 4's over 3's", rank:  209};
{hand: "Two Pair 4's over 2's", rank:  210};
{hand: "Two Pair 3's over 2's", rank:  211};
{hand: "Pair of Aces", rank:  212};
{hand: "Pair of Kings", rank:  213};
{hand: "Pair of Queens", rank:  214};
{hand: "Pair of Jacks", rank:  215};
{hand: "Pair of 10's", rank:  216};
{hand: "Pair of 9's", rank:  217};
{hand: "Pair of 8's", rank:  218};
{hand: "Pair of 7's", rank:  219};
{hand: "Pair of 6's", rank:  220};
{hand: "Pair of 5's", rank:  221};
{hand: "Pair of 4's", rank: 222 };
{hand: "Pair of 3's", rank:  223};
{hand: "Pair of 2's", rank:  224};
{hand: "High Card Ace", rank:  225};
{hand: "High Card King", rank:  226};
{hand: "High Card Queen", rank:  227};
{hand: "High Card Jack", rank:  228};
{hand: "High Card Ten", rank:  229};
{hand: "High Card Nine", rank:  230};
{hand: "High Card Eight", rank:  231};
{hand: "High Card Seven", rank:  232};
{hand: "High Card Six", rank:  233};
{hand: "High Card Five", rank:  234};
{hand: "High Card Four", rank:  235};
{hand: "High Card Three", rank:  236};
{hand: "High Card Two", rank:  237};
